### ISSUE TITLE
Provide option to move processed messages to Trash folder

### ISSUE THREAD

**Issue by FlyingDiver** [FlyingDiver/BetterEmail#5]
Or other named folder, instead of purging messages immediately.

I realized that the plugin wasn't allowing a normal IMAP client function, moving messages to a "Trash" folder instead of deleting them immediately.

**Comment by FlyingDiver** [comment]
https://github.com/FlyingDiver/Indigo-BetterEmail/releases/tag/7.2.1-b1

Pre-release for testing.

**Comment by rycardo** [comment]
Hey, thanks for adding this feature request, I had a busy day, and just came on to download the test version and add the request.  I'll update you about this build either tomorrow or Tuesday depending on how my day goes.  I also saw your question about why not deleting messages, I'll respond to that as well.

**Comment by rycardo** [comment]
Hey, good job on the quick add.  I did some quick test messages, and set up the move to folder being "Processed". I have two IMAP accounts,one is Apple's iCloud the other is the NamesPro server I mentioned earlier. 

On Apple's servers it works perfectly, the messages are moved to the Processed folder.

On NamesPro servers, it does not move the messages. I may have a hint why. All mailbox folders are actually rooted from (if that's the correct term) the INBOX folder. So common folders are:  INBOX, INBOX/Sent, INBOX/Trash, INBOX/Drafts, INBOX/Junk. My Processed folder is actually INBOX/Processed. In Mail, when I set up the account, I tell it the IMAP Path Prefix is INBOX. Then it knows to prefix the folder names with INBOX. I have a few email accounts with different companies, using different mail providers, and they are the same as well. So it's not only NamesPro.

In the IMAP device settings I tried putting in the following for the Move To Folder: 
Processed
INBOX/Processed
INBOX\Processed
and all three give me the same error, with the appropriate path:
 Better Email Debug              Email Indigo IMAP: IDLE Event Received
   Better Email Debug              Email Indigo IMAP: Copying message # 4 to _INBOX\Processed_
   Better Email Debug              Email Indigo IMAP: IDLE Event Received
   Better Email Error              Email Indigo IMAP: Error moving message # 4: ('NO', ['Client tried to access nonexistent namespace. (Mailbox name should probably be prefixed with: INBOX.) (0.001 + 0.000 secs).'])
For the other two tries, the italic part shows
_Processed_ when I tried with that
_INBOX/Processed_ when I tried with that.

I took the 9 lines from your plugin's log file for only the last message, I also XXXed out my name and email address, since I'm posting here plain text.
[plugin copy.log](https://github.com/FlyingDiver/Indigo-BetterEmail/files/1959598/plugin.copy.log)

Maybe it's not a / or \ that is being expected. 

Thanks for your help with this. After receiving your previous message, I moved all the messages to the Processed folder manually, and I have not received either of the errors I had reported.

**Comment by FlyingDiver** [comment]
Try using "/Processed".

**Comment by FlyingDiver** [comment]
Also try "INBOX.Processed".  

This is messy.  See https://blog.fastmail.com/2016/07/13/whats-in-a-name-mailbox-names-via-imap/

**Comment by rycardo** [comment]
Hey,

Look at you being all smart!  You got it, it's "INBOX.Processed". I should have thought of that one. (that was a compliment in case it across out otherwise) I wonder if you can and/or want to check the mailbox path when it's entered in the device's settings. Or maybe just suggest to use . as separators. I would think most people using your plugin are on the techy level, and it's easy enough to see the message didn't move over.

I still have not seen either of the original two errors, so I'm quite confident in your assertion that there was just too many messages. Although that flag one might have been something specific to those messages which were moved over to the Processed folder manually. If that message comes up again, I'll create a new issue.

I also very much like how you copy the message over, then when successful delete the original. Fits in very much with the way I do things as well.

Much of that article I'v seen before, although I don't remember if through them. At some point in my previous work life I used fastmail servers for mail.

Thanks again for putting this together so quickly!! 

R

**Comment by FlyingDiver** [comment]
I looked hard at what it would take to test the Mailbox when the config dialog is verified, but it requires actually connecting to the server at that time.  Which would be difficult, at best.  I'll look at it again.  I'm also going to add a page to the Wiki describing the possible naming schemes.

Also, IMAP doesn't actually have a MOVE command.  So Copy then Delete is the only way to do it.  ;)

**Comment by FlyingDiver** [comment]
Working in 7.2.1.  Punting  mailbox checking for now.
